//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Prg3ParcModel", "FK__mPaciente__ESTAT__267ABA7A", "mEstatusPaciente", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(HamaParcial.mEstatusPaciente), "mPacientes", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HamaParcial.mPaciente))]

// Original file name:
// Generation date: 2/10/2023 8:07:37 AM
namespace HamaParcial
{
    
    /// <summary>
    /// There are no comments for Prg3ParcModel.mEstatusPaciente in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IDESTATUS
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Prg3ParcModel", Name="mEstatusPaciente")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class mEstatusPaciente : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new mEstatusPaciente object.
        /// </summary>
        /// <param name="iDESTATUS">Initial value of IDESTATUS.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static mEstatusPaciente CreatemEstatusPaciente(int iDESTATUS)
        {
            mEstatusPaciente mEstatusPaciente = new mEstatusPaciente();
            mEstatusPaciente.IDESTATUS = iDESTATUS;
            return mEstatusPaciente;
        }
        /// <summary>
        /// There are no comments for property IDESTATUS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int IDESTATUS
        {
            get
            {
                return this._IDESTATUS;
            }
            set
            {
                this.OnIDESTATUSChanging(value);
                this.ReportPropertyChanging("IDESTATUS");
                this._IDESTATUS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDESTATUS");
                this.OnIDESTATUSChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _IDESTATUS;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDESTATUSChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDESTATUSChanged();
        /// <summary>
        /// There are no comments for property DESCRIPCION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string DESCRIPCION
        {
            get
            {
                return this._DESCRIPCION;
            }
            set
            {
                this.OnDESCRIPCIONChanging(value);
                this.ReportPropertyChanging("DESCRIPCION");
                this._DESCRIPCION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DESCRIPCION");
                this.OnDESCRIPCIONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _DESCRIPCION;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDESCRIPCIONChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDESCRIPCIONChanged();
        /// <summary>
        /// There are no comments for mPacientes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Prg3ParcModel", "FK__mPaciente__ESTAT__267ABA7A", "mPacientes")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<mPaciente> mPacientes
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<mPaciente>("Prg3ParcModel.FK__mPaciente__ESTAT__267ABA7A", "mPacientes");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<mPaciente>("Prg3ParcModel.FK__mPaciente__ESTAT__267ABA7A", "mPacientes", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Prg3ParcModel.mPaciente in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IDPACIENTE
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Prg3ParcModel", Name="mPaciente")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class mPaciente : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new mPaciente object.
        /// </summary>
        /// <param name="iDPACIENTE">Initial value of IDPACIENTE.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static mPaciente CreatemPaciente(int iDPACIENTE)
        {
            mPaciente mPaciente = new mPaciente();
            mPaciente.IDPACIENTE = iDPACIENTE;
            return mPaciente;
        }
        /// <summary>
        /// There are no comments for property IDPACIENTE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int IDPACIENTE
        {
            get
            {
                return this._IDPACIENTE;
            }
            set
            {
                this.OnIDPACIENTEChanging(value);
                this.ReportPropertyChanging("IDPACIENTE");
                this._IDPACIENTE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDPACIENTE");
                this.OnIDPACIENTEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _IDPACIENTE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDPACIENTEChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDPACIENTEChanged();
        /// <summary>
        /// There are no comments for property NOMBRES in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NOMBRES
        {
            get
            {
                return this._NOMBRES;
            }
            set
            {
                this.OnNOMBRESChanging(value);
                this.ReportPropertyChanging("NOMBRES");
                this._NOMBRES = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NOMBRES");
                this.OnNOMBRESChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NOMBRES;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNOMBRESChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNOMBRESChanged();
        /// <summary>
        /// There are no comments for property APELLIDOS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string APELLIDOS
        {
            get
            {
                return this._APELLIDOS;
            }
            set
            {
                this.OnAPELLIDOSChanging(value);
                this.ReportPropertyChanging("APELLIDOS");
                this._APELLIDOS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("APELLIDOS");
                this.OnAPELLIDOSChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _APELLIDOS;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAPELLIDOSChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAPELLIDOSChanged();
        /// <summary>
        /// There are no comments for property EXPEDIENTE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<decimal> EXPEDIENTE
        {
            get
            {
                return this._EXPEDIENTE;
            }
            set
            {
                this.OnEXPEDIENTEChanging(value);
                this.ReportPropertyChanging("EXPEDIENTE");
                this._EXPEDIENTE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EXPEDIENTE");
                this.OnEXPEDIENTEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<decimal> _EXPEDIENTE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEXPEDIENTEChanging(global::System.Nullable<decimal> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEXPEDIENTEChanged();
        /// <summary>
        /// There are no comments for property IDENTIFICACION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string IDENTIFICACION
        {
            get
            {
                return this._IDENTIFICACION;
            }
            set
            {
                this.OnIDENTIFICACIONChanging(value);
                this.ReportPropertyChanging("IDENTIFICACION");
                this._IDENTIFICACION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("IDENTIFICACION");
                this.OnIDENTIFICACIONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _IDENTIFICACION;
        internal int ESTATUS;

        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDENTIFICACIONChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDENTIFICACIONChanged();
        /// <summary>
        /// There are no comments for mEstatusPaciente in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Prg3ParcModel", "FK__mPaciente__ESTAT__267ABA7A", "mEstatusPaciente")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public mEstatusPaciente mEstatusPaciente
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<mEstatusPaciente>("Prg3ParcModel.FK__mPaciente__ESTAT__267ABA7A", "mEstatusPaciente").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<mEstatusPaciente>("Prg3ParcModel.FK__mPaciente__ESTAT__267ABA7A", "mEstatusPaciente").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for mEstatusPaciente in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<mEstatusPaciente> mEstatusPacienteReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<mEstatusPaciente>("Prg3ParcModel.FK__mPaciente__ESTAT__267ABA7A", "mEstatusPaciente");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<mEstatusPaciente>("Prg3ParcModel.FK__mPaciente__ESTAT__267ABA7A", "mEstatusPaciente", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for DBhamaPrg in the schema.
    /// </summary>
    public partial class DBhamaPrg : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new DBhamaPrg object using the connection string found in the 'DBhamaPrg' section of the application configuration file.
        /// </summary>
        public DBhamaPrg() : 
                base("name=DBhamaPrg", "DBhamaPrg")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DBhamaPrg object.
        /// </summary>
        public DBhamaPrg(string connectionString) : 
                base(connectionString, "DBhamaPrg")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DBhamaPrg object.
        /// </summary>
        public DBhamaPrg(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "DBhamaPrg")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for mEstatusPacientes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<mEstatusPaciente> mEstatusPacientes
        {
            get
            {
                if ((this._mEstatusPacientes == null))
                {
                    this._mEstatusPacientes = base.CreateQuery<mEstatusPaciente>("[mEstatusPacientes]");
                }
                return this._mEstatusPacientes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<mEstatusPaciente> _mEstatusPacientes;
        /// <summary>
        /// There are no comments for mPacientes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<mPaciente> mPacientes
        {
            get
            {
                if ((this._mPacientes == null))
                {
                    this._mPacientes = base.CreateQuery<mPaciente>("[mPacientes]");
                }
                return this._mPacientes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<mPaciente> _mPacientes;
        /// <summary>
        /// There are no comments for mEstatusPacientes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTomEstatusPacientes(mEstatusPaciente mEstatusPaciente)
        {
            base.AddObject("mEstatusPacientes", mEstatusPaciente);
        }
        /// <summary>
        /// There are no comments for mPacientes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTomPacientes(mPaciente mPaciente)
        {
            base.AddObject("mPacientes", mPaciente);
        }
    }
}
